---
- name: Create Group
  group:
    gid: "{{ haproxy_gid }}"
    name: haproxy

- name: Create User
  user:
    uid: "{{ haproxy_uid }}"
    name: haproxy
    groups: haproxy
    comment: Haproxy
    shell: /sbin/nologin
    home: /var/lib/haproxy
    createhome: no

- name: Install
  yum:
    name: "{{ item }}"
  with_items:
    - haproxy

- name: Send conf templates
  template:
    src: "{{ item }}"
    dest: "{{ item | dirname | regex_replace('^.*\\.\\./templates','') }}/{{ item | basename | regex_replace('\\.j2$','') }}"
    backup: yes
  with_fileglob: "{{ haproxy_conf_templates }}"
  notify:
    - restart haproxy

- name: Service is running and enabled
  service:
    name: haproxy
    state: started
    enabled: yes
