---
- name: Add Yum Repo
  yum_repository:
    file: docker
    name: docker
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    description: Docker Repository
    enabled: no
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
    backup: yes

- name: Install
  yum:
    name: "{{ item }}"
    enablerepo: docker
  with_items:
    - docker-engine

- name: Service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.5.2/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: /usr/bin/docker-compose
    mode: 0755
