---
- name: Install
  yum:
    name: phpMyAdmin
    enablerepo: epel

- name: Send conf templates
  template:
    src: "{{ item }}"
    dest: "{{ item | dirname | regex_replace('^.*\\.\\./templates','') }}/{{ item | basename | regex_replace('\\.j2$','') }}"
    backup: yes
  with_fileglob: "{{ phpmyadmin_conf_templates }}"
  notify:
    - restart httpd
